import { Quiz } from 'services/estyleApi';

export const horizontalBodyshapeContent = {
  [Quiz.HorizontalBodyShapeEnum.Hourglass]: 'The hourglass shape is considered to be a perfectly balanced body.<br/>You really are fortunate woman as your top half perfectly matches the bottom.<br/>You gain weight proportianately and never fall out of balance.You are lucky that you get to keep your nicely shaped waistline, even if your weight moves up.<br/>With your perfectly shaped body, you are always mistaken for a smaller size than you really are, This is very amazing!? What\'s more,most of your clothing fits perfectly and you can afford to wear almost everything.<br/><br/>ADVICE:<br/><br/> As your limitation might come from other factors like vertical proportions, prominent features or any imperfection you are concerned about, (what are you trying to say? It doesn’t quite make sense)..we will mostly concentrate on your prominent features.',
  [Quiz.HorizontalBodyShapeEnum.Triangular]: 'Triangular body shape is probably the most common body shape of all, your hip line is proportionately larger then your waist and bust line.<br/>Your hips doesn\'t have to be huge, but if your bust size is smaller than the hip line you belong to triangular body shape category.Your derriere is usually wider and a big  bigger. Could be flat or rounded.<br/><br/>ADVICE:<br/><br/>Main intention while dressing up would be optically broadening upper part while minimizing your lower part of the body.<br/>We will use \'Eye Up\'  technique to take attention away from your hips and getting closer to hourglass body shape.<br/>As your other limitation might come from other factors like vertical proportions or prominent features we will pay attention to such details and propose the best choices for you.',
  [Quiz.HorizontalBodyShapeEnum.Diamond]: 'Your midsection is proportionately larger than waist and hip line.<br/>Most of your "weight" is usually concentrated in your midsection. However your legs can be your great asset even if you are slightly overweight.<br/><br/>ADVICE:<br/><br/> We will use the \'Slimming Down\' technique for your entire body stressing your midsection.<br/>As it can feels like  you are close to oval body shape your advantage comes out from prominent features that are usually  less problematic with your body shape.<br/>Attention on the chest and right necklines will also help to visually elongate entire body.',
  [Quiz.HorizontalBodyShapeEnum.Rectangular]: 'Your body shape is characterized by thicker waistline that is proportianetely similar to hip line and bust line.<br/>You can "aged" into rectangular shape by thickening your waist or  you can be naturally rectangular. <br/>A rectangular woman optically usually appears shorter and heavier due  to her problematic midsection.<br/><br/>ADVICE:<br/><br/> Main intention while dressing up is to elongate your body and create the illusion of inverted triangular or in best cases, the hourglass body shape.<br/>We can play with \'Eye Up and Eye Down\' technique, use then separatelly or as an combination.<br/>Rectangular body shape provides many posible options for your wardrobe.<br/>However, as your other limitation might come from other factors like vertical proportions or prominent features we will pay attention to such details and propose best choices for you.',
  [Quiz.HorizontalBodyShapeEnum.InvertedTriangular]: 'Your bust line appears greater than your waist and hipline.<br/>If you gain weight it is concentrated in upper part of your body.<br/>Your legs are your greatest assets as they are usually slim.<br/><br/>ADVICE:<br/><br/>Main intention while dressing up is to widen lower part of your body starting at waist line area to balance your bust line.<br/>We will use \'Eye Down\' technique and make sure that your body will be optically closer to ideal body shape.<br/>The key element here is you must have a well fitted bra.',
  [Quiz.HorizontalBodyShapeEnum.Oval]: 'Your body is mostly rounded with no waistline to show. There might be couple limitations while choosing the clothes that comes out from most of the prominent features.<br/><br/>ADVICE:<br/><br/>Main intention while dressing up is to elongate the body, cover imperfections and bring attention upwards to your face and neckline. You should not go for oversized clothing as it just make you look much bigger than you really are.',
};

export const verticalBodyshapeContent = {
  [Quiz.VerticalBodyShapeEnum.Balanced]: 'Your vertical body shape is very fortunate as you belong to balanced body category.<br/>Your body is naturally balanced , your derriere tends to be well placed and shaped.<br/>Having a balanced body is a big advantage that gives you freedom to focus on other parts of your body that you want to emphasize or hide.<br/>It is usually easier than other vertical body shapes.',
  [Quiz.VerticalBodyShapeEnum.LongLegsShortTorso]: 'Your vertical body shape is characterized by long legs and short torso. <br/>Your long legs are one of your best features, you can easily wear shorts and look great in them.<br/>Hovewer, your short torso can add some volume to hip area. Main intention is to create illusion of lower waistline to mute hip part and create more balance body shape.',
  [Quiz.VerticalBodyShapeEnum.ShortLegsLongTorso]: 'Your vertical body shape is characterized by long torso and short legs.<br/>This category is easy to work with as you have many choices that helps you create illusions of a more balanced body which  prolongs your legs at the same time.<br/>You should definitely bring your attention upwards, work with the neckline area, create illusion of higher waistline and always remember to maintain great posture .',
};
