export * from './auth.service';
import { AuthService } from './auth.service';
export * from './clothingBrands.service';
import { ClothingBrandsService } from './clothingBrands.service';
export * from './clothingCategory.service';
import { ClothingCategoryService } from './clothingCategory.service';
export * from './clothingItem.service';
import { ClothingItemService } from './clothingItem.service';
export * from './clothingOccasion.service';
import { ClothingOccasionService } from './clothingOccasion.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './itemAttribute.service';
import { ItemAttributeService } from './itemAttribute.service';
export * from './outfit.service';
import { OutfitService } from './outfit.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './paymentPackage.service';
import { PaymentPackageService } from './paymentPackage.service';
export * from './quiz.service';
import { QuizService } from './quiz.service';
export * from './styleGuideItem.service';
import { StyleGuideItemService } from './styleGuideItem.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './video.service';
import { VideoService } from './video.service';
export const APIS = [AuthService, ClothingBrandsService, ClothingCategoryService, ClothingItemService, ClothingOccasionService, DefaultService, ItemAttributeService, OutfitService, PaymentService, PaymentPackageService, QuizService, StyleGuideItemService, UserService, VideoService];
