/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Service } from './service';


export interface PaymentPackageVariationPatchDto { 
    name?: string;
    interval?: PaymentPackageVariationPatchDto.IntervalEnum;
    services?: Array<Service>;
}
export namespace PaymentPackageVariationPatchDto {
    export type IntervalEnum = 'MONTHLY' | 'QUARTERLY' | 'YEARLY';
    export const IntervalEnum = {
        MONTHLY: 'MONTHLY' as IntervalEnum,
        QUARTERLY: 'QUARTERLY' as IntervalEnum,
        YEARLY: 'YEARLY' as IntervalEnum
    };
}


