/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Service } from './service';


export interface PaymentPackageDto { 
    id: string;
    name: string;
    paymentType: PaymentPackageDto.PaymentTypeEnum;
    services: Array<Service>;
    defaultVariation: string;
    isArchived: boolean;
    createdOn: string;
}
export namespace PaymentPackageDto {
    export type PaymentTypeEnum = 'single' | 'recurring';
    export const PaymentTypeEnum = {
        Single: 'single' as PaymentTypeEnum,
        Recurring: 'recurring' as PaymentTypeEnum
    };
}


