/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Service } from './service';


export interface PaymentPackagePostDto { 
    name: string;
    paymentType: PaymentPackagePostDto.PaymentTypeEnum;
    services: Array<Service>;
}
export namespace PaymentPackagePostDto {
    export type PaymentTypeEnum = 'single' | 'recurring';
    export const PaymentTypeEnum = {
        Single: 'single' as PaymentTypeEnum,
        Recurring: 'recurring' as PaymentTypeEnum
    };
}


