/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizMeasurements { 
    /**
     * Height in cm
     */
    height: number;
    weight: number;
    shoulderSize: number;
    bustSize: number;
    waistSize: number;
    hipSize: number;
    wristSize: number;
    ankleSize: number;
    headToBustSize: number;
    bustToHipSize: number;
    hipToKneeSize: number;
    kneeToFloorSize: number;
    neckSize: number;
}

