/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizMeasurements } from './quizMeasurements';
import { QuizFeatures } from './quizFeatures';


export interface QuizPostDto { 
    measurements: QuizMeasurements;
    fatures: QuizFeatures;
    personalityAnswers: Array<QuizPostDto.PersonalityAnswersEnum>;
}
export namespace QuizPostDto {
    export type PersonalityAnswersEnum = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g';
    export const PersonalityAnswersEnum = {
        A: 'a' as PersonalityAnswersEnum,
        B: 'b' as PersonalityAnswersEnum,
        C: 'c' as PersonalityAnswersEnum,
        D: 'd' as PersonalityAnswersEnum,
        E: 'e' as PersonalityAnswersEnum,
        F: 'f' as PersonalityAnswersEnum,
        G: 'g' as PersonalityAnswersEnum
    };
}


