/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizFeatures { 
    bustSize: QuizFeatures.BustSizeEnum;
    hasLargerArms: boolean;
    hasProblematicMidsection: boolean;
    hasLargerThighsOrHips: boolean;
    hasLargeLegs: boolean;
    shoulderSize: QuizFeatures.ShoulderSizeEnum;
    shoulderShape: QuizFeatures.ShoulderShapeEnum;
}
export namespace QuizFeatures {
    export type BustSizeEnum = 'small' | 'big';
    export const BustSizeEnum = {
        Small: 'small' as BustSizeEnum,
        Big: 'big' as BustSizeEnum
    };
    export type ShoulderSizeEnum = 'narrow' | 'wide';
    export const ShoulderSizeEnum = {
        Narrow: 'narrow' as ShoulderSizeEnum,
        Wide: 'wide' as ShoulderSizeEnum
    };
    export type ShoulderShapeEnum = 'sloping' | 'tapperd';
    export const ShoulderShapeEnum = {
        Sloping: 'sloping' as ShoulderShapeEnum,
        Tapperd: 'tapperd' as ShoulderShapeEnum
    };
}


