/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StyleGuideItemPatchDto { 
    bodytype?: Array<StyleGuideItemPatchDto.BodytypeEnum>;
    prominentFeature?: Array<StyleGuideItemPatchDto.ProminentFeatureEnum>;
    clothingCategory?: string;
    title?: string;
    description?: string;
}
export namespace StyleGuideItemPatchDto {
    export type BodytypeEnum = 'hourglass' | 'triangular' | 'rectangular' | 'invertedTriangular' | 'diamond' | 'oval';
    export const BodytypeEnum = {
        Hourglass: 'hourglass' as BodytypeEnum,
        Triangular: 'triangular' as BodytypeEnum,
        Rectangular: 'rectangular' as BodytypeEnum,
        InvertedTriangular: 'invertedTriangular' as BodytypeEnum,
        Diamond: 'diamond' as BodytypeEnum,
        Oval: 'oval' as BodytypeEnum
    };
    export type ProminentFeatureEnum = 'smallBust' | 'mediumBust' | 'bigBust' | 'narrowShoulders' | 'wideShoulders' | 'slopingShoulders' | 'tapperdShoulders' | 'heavyOrAgedArms' | 'problematicMidsection' | 'largeThighsAndSaddleBags' | 'largeLowerLegs' | 'largeDerriere' | 'flatDerriere' | 'shortPetite' | 'medium' | 'tall' | 'veryThin' | 'overweight' | 'mediumWeight';
    export const ProminentFeatureEnum = {
        SmallBust: 'smallBust' as ProminentFeatureEnum,
        MediumBust: 'mediumBust' as ProminentFeatureEnum,
        BigBust: 'bigBust' as ProminentFeatureEnum,
        NarrowShoulders: 'narrowShoulders' as ProminentFeatureEnum,
        WideShoulders: 'wideShoulders' as ProminentFeatureEnum,
        SlopingShoulders: 'slopingShoulders' as ProminentFeatureEnum,
        TapperdShoulders: 'tapperdShoulders' as ProminentFeatureEnum,
        HeavyOrAgedArms: 'heavyOrAgedArms' as ProminentFeatureEnum,
        ProblematicMidsection: 'problematicMidsection' as ProminentFeatureEnum,
        LargeThighsAndSaddleBags: 'largeThighsAndSaddleBags' as ProminentFeatureEnum,
        LargeLowerLegs: 'largeLowerLegs' as ProminentFeatureEnum,
        LargeDerriere: 'largeDerriere' as ProminentFeatureEnum,
        FlatDerriere: 'flatDerriere' as ProminentFeatureEnum,
        ShortPetite: 'shortPetite' as ProminentFeatureEnum,
        Medium: 'medium' as ProminentFeatureEnum,
        Tall: 'tall' as ProminentFeatureEnum,
        VeryThin: 'veryThin' as ProminentFeatureEnum,
        Overweight: 'overweight' as ProminentFeatureEnum,
        MediumWeight: 'mediumWeight' as ProminentFeatureEnum
    };
}


