/**
 * eStyle server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPatchDto { 
    email?: string;
    role?: UserPatchDto.RoleEnum;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    status?: string;
    type?: string;
}
export namespace UserPatchDto {
    export type RoleEnum = 'standard' | 'admin';
    export const RoleEnum = {
        Standard: 'standard' as RoleEnum,
        Admin: 'admin' as RoleEnum
    };
}


